services:
  ollama:
    image: ollama/ollama
    container_name: ollama
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    environment:
      - OLLAMA_FLASH_ATTENTION=1
      - OLLAMA_KV_CACHE_TYPE=q8_0
    ports:
      - "11434:11434"
    volumes:
      - ollama:/root/.ollama
  openwebui:
    image: ghcr.io/open-webui/open-webui:main
    environment:
      - OLLAMA_BASE_URL=http://jupiter.hl:11434
    ports:
      - "3000:8080"
    volumes:
      - open-webui:/app/backend/data

volumes:
  ollama:
  open-webui: