[DEFAULT]
# Global defaults for macOS models
port = 8001
seed = 3407
flash-attn = on
jinja = true
# macOS typically uses Metal, so n-gpu-layers = 999 ensures full offload
n-gpu-layers = 999
fit = on
temp = 0.6
top-p = 0.95
min-p = 0.01
top-k = 40

[unsloth/MiniMax-M2.1]
ctx-size = 16384
hf = unsloth/MiniMax-M2.1-GGUF:IQ3_XXS
temp = 1.0

[unsloth/MiniMax-M2.5]
batch-size = 2048
ctx-size = 32768
fit = off
hf = unsloth/MiniMax-M2.5-GGUF:UD-IQ3_XXS
mlock = true
n-gpu-layers = 99
temp = 1.0
threads = 12
ubatch-size = 512
cache-type-k = q8_0
cache-type-v = q8_0

[unsloth/GLM-4.7-Flash-REAP]
ctx-size = 131072
hf = unsloth/GLM-4.7-Flash-REAP-23B-A3B-GGUF:Q5_K_XL
temp = 0.7
top-p = 1.00
