[DEFAULT]
# Global defaults for all models
port = 8001
seed = 3407
flash-attn = on
jinja = true
threads = 8
threads-batch = 16
batch-size = 4096
ubatch-size = 4096
cache-type-k = q8_0
cache-type-v = q8_0
fit = on
temp = 0.6
top-p = 0.95
min-p = 0.01
top-k = 40
