[DEFAULT]
# Global defaults for all models
port = 8001
seed = 3407
flash-attn = on
jinja = true
threads = 8
threads-batch = 16
batch-size = 4096
ubatch-size = 4096
cache-type-k = q8_0
cache-type-v = q8_0
fit = on
temp = 0.6
top-p = 0.95
min-p = 0.01
top-k = 40

[unsloth/MiniMax-M2.5]
cache-type-k = q4_0
cache-type-v = q4_0
ctx-size = 16384
fit = off
hf = unsloth/MiniMax-M2.5-GGUF:IQ2_XXS
n-cpu-moe = 80
n-gpu-layers = 81
temp = 1.0
threads = 16
ubatch-size = 128

[unsloth/MiniMax-M2.1]
ctx-size = 16384
hf = unsloth/MiniMax-M2.1-GGUF:IQ3_XXS
temp = 1.0

[unsloth/MiniMax-M2.5 (minimax-m2.5-macos.sh)]
batch-size = 2048
ctx-size = 32768
fit = off
hf = unsloth/MiniMax-M2.5-GGUF:UD-IQ3_XXS
n-gpu-layers = 99
temp = 1.0
threads = 12
ubatch-size = 512

[Devstral-Small-2-24B-Instruct]
ctx-size = 65536
hf = unsloth/Devstral-Small-2-24B-Instruct-2512-GGUF:Q4_K_XL
temp = 0.7
top-p = 0.9

[mradermacher/Nanbeige4.1-3B]
ctx-size = 131072
fit = off
hf = mradermacher/Nanbeige4.1-3B-GGUF:F16
n-gpu-layers = 99

[unsloth/Nemotron-3-Nano-30B-A3B-A3B]
ctx-size = 65536
fit = off
hf = unsloth/Nemotron-3-Nano-30B-A3B-GGUF:Q4_K_XL
n-cpu-moe = 30
n-gpu-layers = 99
threads = 16

[unsloth/NVIDIA-Nemotron-3-Super-120B-A12B]
ctx-size = 32768
hf = unsloth/NVIDIA-Nemotron-3-Super-120B-A12B-GGUF:UD-Q4_K_XL

[unsloth/NVIDIA-Nemotron-3-Super-120B-A12B (nemotron-3-super_UD_Q3_K_XL.sh)]
ctx-size = 131072
hf = unsloth/NVIDIA-Nemotron-3-Super-120B-A12B-GGUF:UD-Q3_K_XL

[unsloth/gpt-oss-120B]
chat-template-kwargs = {"reasoning_effort": "high"}
ctx-size = 32768
hf = unsloth/gpt-oss-120b-GGUF:F16
temp = 1.0
top-k = 100.0
top-p = 1.0

[unsloth/Qwen3-Coder-Next]
ctx-size = 262144
hf = unsloth/Qwen3-Coder-Next-GGUF:Q4_K_XL
min-p = 0.00
temp = 1.0

[unsloth/Qwen3.5-122B-A10B]
batch-size = 2048
ctx-size = 65536
hf = unsloth/Qwen3.5-122B-A10B-GGUF:UD-Q4_K_XL
min-p = 0.00
presence-penalty = 0.05
repeat_penalty = 1.05
top-k = 20
ubatch-size = 2048

[unsloth/Qwen3.5-122B-A10B (qwen3.5-122B-A10B.sh)]
ctx-size = 131072
hf = unsloth/Qwen3.5-122B-A10B-GGUF:UD-Q4_K_XL
min-p = 0.00
presence-penalty = 1.1
repeat_penalty = 1.05
top-k = 20

[unsloth/Qwen3.5-122B-A10B (qwen3.5-122B-A10B_UD_Q3_K_XL.sh)]
ctx-size = 262144
hf = unsloth/Qwen3.5-122B-A10B-GGUF:UD-Q3_K_XL
min-p = 0.00
presence-penalty = 1.1
repeat_penalty = 1.05
top-k = 20

[unsloth/Qwen3.5-27B]
ctx-size = 131072
hf = unsloth/Qwen3.5-27B-GGUF:UD-Q4_K_XL
min-p = 0.00
presence-penalty = 1.1
repeat_penalty = 1.05
top-k = 20

[unsloth/Qwen3.5-35B-A3B]
cache-type-k = bf16
cache-type-v = bf16
ctx-size = 131072
hf = unsloth/Qwen3.5-35B-A3B-GGUF:UD-Q4_K_XL
min-p = 0.00
presence-penalty = 1.1
repeat_penalty = 1.05
top-k = 20

[unsloth/Qwen3.5-397B-A17B]
batch-size = 2048
ctx-size = 8192
hf = unsloth/Qwen3.5-397B-A17B-GGUF:UD-TQ1_0
n-gpu-layers = 99
temp = 1.0
threads = 12
ubatch-size = 512

[unsloth/Qwen3.5-9B]
ctx-size = 131072
hf = unsloth/Qwen3.5-9B-GGUF:UD-Q8_K_XL
min-p = 0.00
presence-penalty = 0.05
repeat_penalty = 1.05
top-k = 20

[AesSedai/Step-3.5-Flash]
ctx-size = 262144
hf = AesSedai/Step-3.5-Flash-GGUF:IQ3_XXS
min-p = 0.00

[Tesslate/OmniCoder-9B]
ctx-size = 262144
hf = Tesslate/OmniCoder-9B-GGUF:Q8_0
presence-penalty = 0.0
temp = 0.4

[unsloth/GLM-4.5-Air]
ctx-size = 16384
hf = unsloth/GLM-4.5-Air-GGUF:Q5_K_XL
n-gpu-layers = 999
temp = 1.0
threads = -1

[unsloth/GLM-4.7-Flash-REAP]
ctx-size = 131072
hf = unsloth/GLM-4.7-Flash-REAP-23B-A3B-GGUF:Q5_K_XL
temp = 0.7
top-p = 1.00

[unsloth/GLM-4.7-Flash-REAP (glm-4.7-flash-reap.sh)]
ctx-size = 16384
hf = unsloth/GLM-4.7-Flash-REAP-23B-A3B-GGUF:Q4_K_XL
temp = 0.7
top-p = 1.00

[unsloth/GLM-4.7-Flash]
ctx-size = 131072
hf = unsloth/GLM-4.7-Flash-GGUF:Q8_K_XL
temp = 0.7
top-p = 1.00

